# https://crontab.guru/crontab.5.html

name: Check for l10n updates

on:

  workflow_call:

jobs:
  update-translations:
    runs-on: windows-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v3

    - name: Push changes
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        git remote add l10n https://github.com/nvdaaddons/${{ github.repository.name }}
        git fetch l10n
        git reset l10n/stable addon/doc addon/locale
        git commit -m "Update translations"
        git pull
        git push
        
        