name: Generate NVDAoutputs

on:
  workflow_dispatch:

jobs:

  nvda:
  
    name: NVDA
  
    runs-on: windows-2019

    steps:
    - name: Setup Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        architecture: x86
    - name: Checkout NVDA
      uses: actions/checkout@v4
      with:
        repository: nvdaes/nvda
        ref: addonStore-base
        submodules: true
        path: nvda
    - name: Prepare NVDA's source tree
      run: |
        cd nvda
        scons source
      shell: cmd
    - name: Create archive
      run: Compress-Archive nvda nvda.zip
    - name: Upload outputs
      uses: actions/upload-artifact@v3
      with:
        name: nvda-outputs
        path: nvda.zip
