name: Check for MyPy type hints

on:

  workflow_call:
  
jobs:
  mypy:
    runs-on: windows-latest

    steps:
    - name: Checkout reusable workflows
      uses: actions/checkout@v4
      with:
        repository: nvdaes/nvdaAddonWorkflows
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: code
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Install dependencies
      run: pip install mypy
    - name: MyPy
      run: python -m mypy code/addon
