name: Build and test NVDA add-on

on:
  workflow_call

jobs:

  addon:

    name: addon

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install scons markdown
        sudo apt update
        sudo apt install gettext
    - name: Build add-on
      run: scons version=${{ github.sha }}
    - name: Upload add-on
      uses: actions/upload-artifact@v3
      with:
        name: nvda-addon
        path: "*.nvda-addon"
    - name: Build pot
      run: scons pot version=${{ github.sha }}
    - name: Upload pot
      uses: actions/upload-artifact@v3
      with:
        name: pot-file
        path: "*.pot"

        
  nvda:
  
    name: NVDA
  
    needs: addon
  
    runs-on: windows-2019

    steps:

    - name: Cache NVDA
      id: cache-nvda
      uses: actions/cache@v3
      with:
        path: nvda
        key: ${{ runner.os }}-nvda-2022.2
    - name: Set up Python 3.7 x86
      if: steps.cache-nvda.outputs.cache-hit != 'true'
      uses: actions/setup-python@v3
      with:
        python-version: 3.7
        architecture: x86
    - name: Checkout NVDA
      if: steps.cache-nvda.outputs.cache-hit != 'true'
      uses: actions/checkout@v3
      with:
        repository: nvaccess/nvda
        submodules: true
        path: nvda
        href: release_2022.2
    - name: Prepare NVDA's source tree
      if: steps.cache-nvda.outputs.cache-hit != 'true'
      run: |
        cd nvda
        scons source
      shell: cmd
    - name: Download add-on
      uses: actions/download-artifact@v3
      with:
        name: nvda-addon
    - name: Download pot
      uses: actions/download-artifact@v3
      with:
        name: pot-file
    - name: Copy add-on
      run: |
        move *.nvda-addon addon.zip
        Expand-Archive addon.zip nvda\source\userConfig\addons\addon
    - name: Start NVDA
      run: |
        cd source
        runnvda -m --debug-logging
        ping 127.0.0.1 /n 20
      shell: cmd
    - name: Quit NVDA
      run: |
        cd source
        runnvda -q
        ping 127.0.0.1 /n 20
      shell: cmd
    - name: Upload log
      uses: actions/upload-artifact@v3
      with:
        name: nvda-log
        path: source\nvda.log
    - name: Remove add-on
      run: Remove-Item nvda\source\userConfig\addons\addon -Recurse
    - name: Check pot
      run: |
        move *.pot nvda\tests\nvda.pot
        cd nvda\tests
        python checkPot.py nvda.pot > potResults.txt
        type potResults.txt
        Remove-Item nvda.pot
        If (Select-String -Path potResults.txt -Pattern 'Message has no translator comment' -SimpleMatch) {exit 1}
